### ISSUE TITLE
Wacky watch messes up with the game's turn count

### ISSUE THREAD

**Issue by Rancma987** [Rainchus/Mp3-Combination#10]
Someone played the wacky watch on turn 13/20. After this happened, the game thinks we are on turn 16/20 after every turn (the game plays the last 5 turns event after every turn). The game only goes back to turn 16 when a minigame from MP1 or MP2 is played at the end of the turn (or at least that's what I'm assuming, since the game went to turn 17 after playing a MP3 minigame).

Played on Project64 with a custom save file. Every minigame was activated.

**Comment by Rainchus** [comment]
Thanks for the report, there was a quite silly oversight in the code. [v0.1.7](https://github.com/Rainchus/Mp3-Combination/releases/tag/v0.1.7) should address and fix this

**Comment by Rainchus** [comment]
I'm assuming this is fixed (from my testing it should be) so I'm going to close the issue
