### ISSUE TITLE
Attempted to patch but mod does not display minigame list. 

### ISSUE THREAD

**Issue by Chromelement** [Rainchus/Mp3-Combination#2]
I tried the method used in the link but when I tried pressing Z to load the minigame list, nothing happened. I noticed that when patching the roms, the output gives out the mp3-mp2-mp1 file but without the "combo" part, so I'm unsure if that has something to do with it.

**Comment by Rainchus** [comment]
It sounds like the patcher created the combined rom, but didn't actually patch them at all. Can you run `./patcher.exe` from the command line and see what the output is? The expected output is something like
```
C:\Users\Rainchus\Desktop\Mp3-Combination\patcher [main ≡]> ./patcher.exe
Checksum for roms/mp3.z64 is valid (big-endian).
Checksum for roms/mp2.z64 is valid (big-endian).
Checksum for roms/mp1.z64 is valid (big-endian).
Files mp3.z64, mp2.z64, and mp1.z64 successfully merged into mp3-mp2-mp1.z64.
Applying mp3-mp2-mp1-combo.bps to mp3-mp2-mp1.z64...
The patch was applied successfully!
Patch applied successfully, output written to mp3-mp2-mp1-combo.z64.```

**Comment by Rainchus** [comment]
The patcher now deletes the combined rom and only outputs a .z64 of the rom patched with the mod. This should clear up the confusion
