### ISSUE TITLE
Hammer Drop loaded Bumber Ball Maze

### ISSUE THREAD

**Issue by Rancma987** [Rainchus/Mp3-Combination#3]
Played on Project64-MPN.

The roulette landed on Hammer Drop but Bumper Ball Maze was the minigame that was loaded.

**Comment by Rainchus** [comment]
Thanks for the report, this is fixed now as of [this](https://github.com/Rainchus/Mp3-Combination/commit/224a1bc74811f68d8cea8899051a50c8ba4b4c09) commit.
