### ISSUE TITLE
Black screen when loading minigame

### ISSUE THREAD

**Issue by boobell-1** [Rainchus/Mp3-Combination#4]
2/5 times when loading a mini game, the screen has gone black and I had to quit the emulation. 

The three times that games loaded, they were all native MP3 mini games. 
One time loading failed, it was a MP2 mini game.
The other time it failed, it was a native MP3 mini game.

**Comment by boobell-1** [comment]
Playing on project 64

**Comment by Rainchus** [comment]
What version of project64 is this?

**Comment by boobell-1** [comment]
I was using 3.0.1.5664. I just switched to 4.0.0.6162 (I couldn't find 4.0.0.5746). 

The problem is still occurring. I think I originally misunderstood the mini-game naming convention. I think it gets hung up whenever loading mini games from either MP1 or MP2 and works when loading mini games from MP3.

**Comment by Rainchus** [comment]
Do you have daisy or waluigi in your game? I tried to prevent selecting them as they crash in mp1 and mp2, but there was an oversight in my approach

**Comment by Rainchus** [comment]
If it was related to daisy/waluigi, they should no longer be able to be selected as of [this](https://github.com/Rainchus/Mp3-Combination/releases/tag/v0.1.1) release

**Comment by boobell-1** [comment]
Yes! That was it. 

I had separately wondered how those characters were handled, but didn't put it together to think about it being the problem here. 

The games seem to be loading just fine now. 

Thanks!
