### ISSUE TITLE
It is possible to select Daisy and Waluigi

### ISSUE THREAD

**Issue by Haruwolf** [Rainchus/Mp3-Combination#6]
The game not allow to select that characters because they don't exist on MP1 and MP2, but it's possible to select them if you select CPU Peach or DK.

**Comment by Rainchus** [comment]
Thanks for the report. Waluigi and daisy should no longer be able to be selected as of [this](https://github.com/Rainchus/Mp3-Combination/commit/14478eeb9647ed37df320cd3c74dfa413be250f8) commit
